name: Run API Tests with Jest
on:
  pull_request:
    branches: [ master ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12
      - run: yarn
      - run: yarn test
        env: 
          NODE_ENV: test
          TEST_DB_CONNECT: ${{ secrets.TEST_DB_CONNECT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      - run: yarn build
